### ISSUE TITLE
Rich Markdown text is broken

### ISSUE THREAD

**Issue by piperswe** [ID10T-Errors/ID10T-Errors.github.io#28]
Here's your chance to learn CSS, @ztaylor54 (in other words for some reason Firefox's debugger is broken in my computer)

**Comment by ztaylor54** [comment]
It's strange, markdown is performing just fine on mobile. I'll look into it.

**Comment by piperswe** [comment]
Maybe it's just Firefox.

**Comment by ztaylor54** [comment]
No, Chrome is broken too.

**Comment by piperswe** [comment]
Also, I saw that the markdown was being turned into HTML properly, as the elements were there. It's a CSS problem.

**Comment by ztaylor54** [comment]
Ok, hold on. I saw another thing I could try.

**Comment by piperswe** [comment]
It has to do with everything getting `font: inherit`

**Comment by ztaylor54** [comment]
I'm driving, call me on my cell

**Comment by ztaylor54** [comment]
I will not sleep tonight until I figure this out.

**Comment by piperswe** [comment]
Oh no.

**Comment by ztaylor54** [comment]
Why "Oh no." ?

**Comment by piperswe** [comment]
You'll be up all night. (jk, it actually might be very easy)

**Comment by ztaylor54** [comment]
Fixing to try without `font: inherit`. It seems to only be for a "CSS Reset", and many browsers will already support the fonts we are using.

**Comment by ztaylor54** [comment]
**The good news:**
**_It's not broken**_  

**The bad news:**
**_It didn't fix the problem**_

**Comment by ztaylor54** [comment]
I found the issue. `skel.min.js` is breaking everything. After the markdown is rendered on the site, `skel`'s CSS is converting it all to plaintext.

**Comment by ztaylor54** [comment]
I HAVE GOOD NEWS:

`skel.min.js` is the culprit. It's ruining everything. I just **_completely**_ broke the website, but **THE MARKDOWN WORKS**. Revert the pull request in the morning once you've seen that the markdown is indeed working.

I think the next step is to actually write the styles for `skel`, rather that use a huge ugly "cover-all" that we have right now.

**Comment by ztaylor54** [comment]
Also, make sure to look at the changes I made. I simply commented out the stuff that was altering text on the page. It didn't matter that the `html` was correct, because it was simply being re-styled by `skel`.

**Comment by ztaylor54** [comment]
Better, but still terrible.

**Comment by piperswe** [comment]
It's because of formatting in the Markdown file. I PR'd a fix.
