### ISSUE TITLE
Email on website shouldn't be tied to BISD

### ISSUE THREAD

**Issue by ztaylor54** [ID10T-Errors/ID10T-Errors.github.io#6]
I think the email should be one of our personal emails, as we will continue to have this team well beyond Brenham High School, and I would also hate to give the school any claim to our own creation. I suggest `ztaylor54@gmail.com`, as I will be the one organizing the our competition next year.

**Comment by piperswe** [comment]
I think we should have a domain name like id10t.site ($3.88/yr at Namecheap) and have emails there.

**Comment by ztaylor54** [comment]
ctftoolkit.com is like $3 for the first year and $10 after that from godaddy. I like it better and it could be our homepage, email host, and feature our main project, the toolkit.

**Comment by piperswe** [comment]
http://www.blogmarketingacademy.com/godaddy-review/

**Comment by ztaylor54** [comment]
Huh. I've never had any issues and I've used them for my father's site http://andytaylorlaw.com/ for years.

**Comment by ztaylor54** [comment]
Here's what I've got so far:
![flag{it_pays_to_plan_ahead}](http://i.imgur.com/D8q1Lwr.png)

**Comment by piperswe** [comment]
Why is this assigned to me?

**Comment by ztaylor54** [comment]
I did that a while back. I'll work out email forwarding soon.
